name: routine-assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - perl-digest-sha=5.88
  - fastp=0.23.1
  - filtlong=0.2.1
  - nanoq=0.9.0
  - unicycler=0.4.8
  - spades=3.13.0
  - samtools=1.13
  - prokka=1.14.5
  - quast=5.0.2
  - bandage=0.8.1
  - shovill=1.0.9
